### PR TITLE
Resource Promisified

### PR DESCRIPTION
**Pull request by theslyone**
- Minor update to supports promise (then, catch) based resource calls.
- Callback function still supported

### CODE REVIEW

**Comment by Subomi** [comment]
Hello, i think landing this update should be on v2.0.0 and not on 1.x again. check the open issue #14

**Comment by kehers** [comment]
Hi @theslyone , thanks for the PR.
There are some fixes required in the package.json file though. Version (we use [semver](http://semver.org)), author and description needs to be corrected.

Thanks.

**Comment by theslyone** [comment]
@Subomi I have only just extended the functionality to support promises, no breaking change and hence I don't quite think a major version change is necessary for this

**Comment by theslyone** [comment]
@kehers Version, author and description issues corrected as advised. Kindly verify

**Comment by Subomi** [comment]
@theslyone sorry for the long overdue delay on this PR. The callback and then promise handler are not chaining and produce sort of detached ends. Add this piece of test to your test/customer.js to show this bug.

     // To test callback & then chaining
      it("create new customer, parse in callback and enter then handler", function(done) {
        paystack.customer.create({
           first_name: 'Opeyemi',
           last_name: 'Obembe',
          email: 'kehers@gmail.com'
      }, function(error, body) {
      	// callback should parse response and return an object
      	return {'name': 'subomi'};
      }).then(function(body) {
       // callback is called, but then handler does not show its processing, but returns initial api response
      	expect(body).to.have.property('name')
      	done();
      }).catch(function(error) {
      	return done(error);
      });
  
    });

I want to push a fix for that bug, please provide collaborator push access to your fork. Thanks.

**Comment by Subomi** [comment]
Please, check to see if all tests pass.

**Comment by theslyone** [comment]
@Subomi Travis reports a success on all tests.

**Comment by Subomi** [comment]
Merged PR to branch v2.0.0. Other upgrades would be pushed their before merging in master. please see issue #14

**Pull request closed without merging**
