### PR TITLE
added bank resource, updated README, optimized variable names

### PR DESCRIPTION
**Pull request by itswisdomagain**

### CODE REVIEW

**Comment by itswisdomagain** [comment]
@Subomi Do I have to include my test key in package.json? That's what's causing the test to fail...

**Comment by subomi** [comment]
You have to set your secret key as an environment variable named "KEY", for local testing. 

The errors from the build is already informative of the kind of error. Once tests pass locally, then you can push again.

**Comment by itswisdomagain** [comment]
@Subomi Local test passes when I set the environment variable locally. How do I set the environment variable for travis? Will it be wise to include my paystack secret key in the package.json file and push?

**Comment by subomi** [comment]
Hey wisdom, 

It appears the issue was really as a result of the environment variables. Travis removes sensitive information like this away from the build environment as this would allow people to illegally just create a fork to steal important information like secret keys and so allow only those that have write access to a repository to use stored environment variable.

So in your case, your PR did not have access to the stored environment variable in Travis.

The solution was i created a dev branch, merged your fork's master branch into it and created a PR back into this master. 

You can see that in #23 

I will be closing this PR now, to follow up on this continue pushing to your master, and i will continue fetching & merging, its just a work around for now.

**Pull request closed without merging**
